# Fly.io configuration for DevKraft RAG Streamlit UI
# Deploy with: fly launch --config fly-streamlit.toml
# Set API_URL with: fly secrets set API_URL=https://devkraft-rag-api.fly.dev

app = "devkraft-rag-ui"
primary_region = "iad"  # US East (change to your preferred region)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "echo 'DevKraft RAG UI deployed'"
