# Fly.io configuration for DevKraft RAG API
# Deploy with: fly launch --config fly.toml
# Set secrets with: fly secrets set GEMINI_API_KEY=xxx QDRANT_API_KEY=xxx HF_TOKEN=xxx MONGO_URI=xxx

app = "devkraft-rag-api"
primary_region = "iad"  # US East (change to your preferred region)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "echo 'DevKraft RAG API deployed'"
