services:
  # FastAPI Backend Service
  - type: web
    name: devkraft-rag-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false

  # Streamlit Frontend Service
  - type: web
    name: devkraft-rag-ui
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_URL
        fromService:
          type: web
          name: devkraft-rag-api
          envVarKey: RENDER_EXTERNAL_URL
